import type { FluidConfig } from "../app/config";

/** Shared calm hero presentation: close crop, modest grid, slow time. */
const heroBase = {
  simResolution: 192,
  dyeResolution: 384,
  pressureIterations: 24,
  noiseTime: 0.06,
  viewZoom: 2.2,
  warmupSteps: 28,
  maxDt: 1 / 30,
  pointerEnabled: false,
  videoReveal: 0,
  youtubeUrl: "",
} as const;

/** Hand-authored page heroes — not gallery presets. */
export const PAGE_HEROES: Record<string, Partial<FluidConfig>> = {
  index: {
    ...heroBase,
    vorticity: 18,
    velocityDecay: 0.5,
    dyeDecay: 0.01,
    seedVelocityScale: 8,
    composerStrength: 22,
    composerBroad: 1.35,
    composerMedium: 0.85,
    composerFine: 0.4,
    noiseScale: 3.2,
    noiseType: "simplex",
    dyeInject: 0.28,
    contrast: 2.35,
    colorTweenSpeed: 0.01,
    wiggleAmount: 0.1,
    windStrength: 8,
    backgroundMode: "gradient",
    backgroundColor: "#071426",
    backgroundColorB: "#2a1140",
    materials: [
      {
        id: "cyan",
        name: "Ion cyan",
        enabled: true,
        color: "#2CF0D4",
        colorB: "#4AA8FF",
        viscosity: 0.07,
        roughness: 0.2,
        metallic: 0.1,
        sheen: 0.7,
        glow: 0.55,
      },
      {
        id: "night",
        name: "Ultraviolet",
        enabled: true,
        color: "#120C3A",
        colorB: "#2A0F45",
        viscosity: 0.22,
        roughness: 0.55,
        metallic: 0.05,
        sheen: 0.55,
        glow: 0.1,
      },
      {
        id: "rose",
        name: "Plasma rose",
        enabled: true,
        color: "#FF4F9A",
        colorB: "#A45CFF",
        viscosity: 0.1,
        roughness: 0.24,
        metallic: 0.18,
        sheen: 0.7,
        glow: 0.52,
      },
      {
        id: "ice",
        name: "Glacial light",
        enabled: true,
        color: "#C8FFF8",
        colorB: "#A8C4FF",
        viscosity: 0.05,
        roughness: 0.28,
        metallic: 0.22,
        sheen: 0.65,
        glow: 0.28,
      },
    ],
    emitters: [
      {
        id: "Cyan ribbons",
        name: "Cyan ribbons",
        enabled: true,
        materialId: "cyan",
        kind: "field",
        rate: 0.9,
        radius: 0.02,
        uvX: 0.5,
        uvY: 0.5,
        noiseOffset: 0,
      },
      {
        id: "Violet depths",
        name: "Violet depths",
        enabled: true,
        materialId: "night",
        kind: "field",
        rate: 1,
        radius: 0.02,
        uvX: 0.5,
        uvY: 0.5,
        noiseOffset: 1.4,
      },
      {
        id: "Rose bloom",
        name: "Rose bloom",
        enabled: true,
        materialId: "rose",
        kind: "point",
        rate: 0.7,
        radius: 0.04,
        uvX: 0.72,
        uvY: 0.68,
        noiseOffset: 0,
      },
      {
        id: "Ice filament",
        name: "Ice filament",
        enabled: true,
        materialId: "ice",
        kind: "point",
        rate: 0.45,
        radius: 0.01,
        uvX: 0.18,
        uvY: 0.3,
        noiseOffset: 0.5,
      },
    ],
    windStations: [
      {
        id: "Rising arc",
        name: "Rising arc",
        enabled: true,
        uvX: 0.7,
        uvY: 0.55,
        heading: 0.22,
        speed: 0.16,
        spin: 0.08,
        radius: 0.28,
      },
      {
        id: "Returning arc",
        name: "Returning arc",
        enabled: true,
        uvX: 0.28,
        uvY: 0.35,
        heading: 0.72,
        speed: 0.14,
        spin: -0.06,
        radius: 0.26,
      },
    ],
    valueEmitters: [
      {
        id: "breath",
        name: "Slow current",
        enabled: true,
        kind: "sine",
        rate: 0.012,
        phase: 0.2,
        from: 0.04,
        to: 0.08,
        scale: 1,
        band: 0,
      },
    ],
    valueBindings: [
      { id: "current", emitterId: "breath", path: "noiseTime", amount: 0.5 },
    ],
  },
  settings: {
    ...heroBase,
    viewZoom: 2.05,
    vorticity: 9,
    velocityDecay: 0.9,
    dyeDecay: 0.018,
    seedVelocityScale: 4,
    composerStrength: 12,
    composerBroad: 0.9,
    composerMedium: 0.55,
    composerFine: 0.25,
    noiseScale: 2.6,
    noiseType: "perlin",
    dyeInject: 0.18,
    contrast: 1.85,
    colorTweenSpeed: 0.006,
    wiggleAmount: 0.05,
    windStrength: 4,
    backgroundMode: "solid",
    backgroundColor: "#e8e4d6",
    backgroundColorB: "#e8e4d6",
    materials: [
      {
        id: "ink",
        name: "Indigo ink",
        enabled: true,
        color: "#2A3F6B",
        colorB: "#1A2A48",
        viscosity: 0.35,
        roughness: 0.55,
        metallic: 0.05,
        sheen: 0.4,
        glow: 0.02,
      },
      {
        id: "glass",
        name: "Sea glass",
        enabled: true,
        color: "#7EB8B2",
        colorB: "#A8D4CF",
        viscosity: 0.2,
        roughness: 0.35,
        metallic: 0.15,
        sheen: 0.55,
        glow: 0.08,
      },
      {
        id: "wash",
        name: "Warm wash",
        enabled: true,
        color: "#D8CBB0",
        colorB: "#C4B49A",
        viscosity: 0.45,
        roughness: 0.7,
        metallic: 0,
        sheen: 0.25,
        glow: 0,
      },
      {
        id: "line",
        name: "Fine line",
        enabled: true,
        color: "#4A6FA5",
        colorB: "#6F92C4",
        viscosity: 0.15,
        roughness: 0.4,
        metallic: 0.1,
        sheen: 0.45,
        glow: 0.05,
      },
    ],
    emitters: [
      {
        id: "Tide body",
        name: "Tide body",
        enabled: true,
        materialId: "wash",
        kind: "field",
        rate: 0.55,
        radius: 0.03,
        uvX: 0.5,
        uvY: 0.5,
        noiseOffset: 0,
      },
      {
        id: "Ink plume",
        name: "Ink plume",
        enabled: true,
        materialId: "ink",
        kind: "point",
        rate: 0.55,
        radius: 0.028,
        uvX: 0.35,
        uvY: 0.6,
        noiseOffset: 0,
      },
      {
        id: "Glass trail",
        name: "Glass trail",
        enabled: true,
        materialId: "glass",
        kind: "point",
        rate: 0.4,
        radius: 0.016,
        uvX: 0.7,
        uvY: 0.32,
        noiseOffset: 0.8,
      },
      {
        id: "Fine tendril",
        name: "Fine tendril",
        enabled: true,
        materialId: "line",
        kind: "point",
        rate: 0.35,
        radius: 0.008,
        uvX: 0.55,
        uvY: 0.22,
        noiseOffset: 1.2,
      },
    ],
    windStations: [
      {
        id: "Soft drift",
        name: "Soft drift",
        enabled: true,
        uvX: 0.45,
        uvY: 0.5,
        heading: 0.05,
        speed: 0.1,
        spin: 0.03,
        radius: 0.4,
      },
    ],
    valueEmitters: [],
    valueBindings: [],
  },
  hero: {
    ...heroBase,
    viewZoom: 2.3,
    vorticity: 11,
    velocityDecay: 1.2,
    dyeDecay: 0.008,
    seedVelocityScale: 3.5,
    composerStrength: 10,
    composerBroad: 0.55,
    composerMedium: 1.1,
    composerFine: 1.4,
    noiseScale: 6.5,
    noiseType: "value",
    dyeInject: 0.3,
    contrast: 2.6,
    colorTweenSpeed: 0.004,
    wiggleAmount: 0.04,
    windStrength: 3.5,
    backgroundMode: "gradient",
    backgroundColor: "#0b1016",
    backgroundColorB: "#3a2818",
    materials: [
      {
        id: "gold",
        name: "Brushed gold",
        enabled: true,
        color: "#E0B46A",
        colorB: "#B88848",
        viscosity: 0.7,
        roughness: 0.28,
        metallic: 0.9,
        sheen: 0.75,
        glow: 0.04,
      },
      {
        id: "stone",
        name: "Obsidian",
        enabled: true,
        color: "#121820",
        colorB: "#1C1418",
        viscosity: 0.85,
        roughness: 0.2,
        metallic: 0.65,
        sheen: 0.5,
        glow: 0,
      },
      {
        id: "copper",
        name: "Copper seam",
        enabled: true,
        color: "#C45E35",
        colorB: "#D87848",
        viscosity: 0.5,
        roughness: 0.38,
        metallic: 0.85,
        sheen: 0.6,
        glow: 0.03,
      },
      {
        id: "silver",
        name: "Pale alloy",
        enabled: true,
        color: "#E2DCC0",
        colorB: "#B8C0BC",
        viscosity: 0.45,
        roughness: 0.22,
        metallic: 0.92,
        sheen: 0.7,
        glow: 0.02,
      },
    ],
    emitters: [
      {
        id: "Gold folds",
        name: "Gold folds",
        enabled: true,
        materialId: "gold",
        kind: "field",
        rate: 0.65,
        radius: 0.016,
        uvX: 0.5,
        uvY: 0.5,
        noiseOffset: 0,
      },
      {
        id: "Stone body",
        name: "Stone body",
        enabled: true,
        materialId: "stone",
        kind: "field",
        rate: 1,
        radius: 0.022,
        uvX: 0.5,
        uvY: 0.5,
        noiseOffset: 2,
      },
      {
        id: "Copper seam",
        name: "Copper seam",
        enabled: true,
        materialId: "copper",
        kind: "point",
        rate: 0.5,
        radius: 0.02,
        uvX: 0.78,
        uvY: 0.28,
        noiseOffset: 0,
      },
      {
        id: "Alloy thread",
        name: "Alloy thread",
        enabled: true,
        materialId: "silver",
        kind: "point",
        rate: 0.35,
        radius: 0.007,
        uvX: 0.22,
        uvY: 0.75,
        noiseOffset: 0.4,
      },
    ],
    windStations: [
      {
        id: "Slow fold",
        name: "Slow fold",
        enabled: true,
        uvX: 0.68,
        uvY: 0.48,
        heading: 0.1,
        speed: 0.08,
        spin: 0.05,
        radius: 0.38,
      },
      {
        id: "Counterfold",
        name: "Counterfold",
        enabled: true,
        uvX: 0.3,
        uvY: 0.62,
        heading: 0.58,
        speed: 0.07,
        spin: -0.035,
        radius: 0.32,
      },
    ],
    valueEmitters: [
      {
        id: "breath",
        name: "Metal breath",
        enabled: true,
        kind: "sine",
        rate: 0.01,
        phase: 0.4,
        from: 0.03,
        to: 0.07,
        scale: 1,
        band: 0,
      },
    ],
    valueBindings: [
      { id: "current", emitterId: "breath", path: "noiseTime", amount: 0.4 },
    ],
  },
  gallery: {
    ...heroBase,
    viewZoom: 2.25,
    vorticity: 14,
    velocityDecay: 1.0,
    dyeDecay: 0.01,
    seedVelocityScale: 5,
    composerStrength: 14,
    composerBroad: 0.6,
    composerMedium: 1.3,
    composerFine: 0.45,
    noiseScale: 3.0,
    noiseType: "value",
    dyeInject: 0.26,
    contrast: 2.55,
    colorTweenSpeed: 0.005,
    wiggleAmount: 0.06,
    windStrength: 5,
    backgroundMode: "solid",
    backgroundColor: "#061228",
    backgroundColorB: "#061228",
    materials: [
      {
        id: "cobalt",
        name: "Cobalt",
        enabled: true,
        color: "#2F6FFF",
        colorB: "#1A4DB8",
        viscosity: 0.18,
        roughness: 0.2,
        metallic: 0.55,
        sheen: 0.8,
        glow: 0.2,
      },
      {
        id: "ice",
        name: "Ice edge",
        enabled: true,
        color: "#E8F4FF",
        colorB: "#A8D0FF",
        viscosity: 0.08,
        roughness: 0.15,
        metallic: 0.7,
        sheen: 0.9,
        glow: 0.15,
      },
      {
        id: "depth",
        name: "Abyss",
        enabled: true,
        color: "#071830",
        colorB: "#0A2448",
        viscosity: 0.4,
        roughness: 0.45,
        metallic: 0.2,
        sheen: 0.35,
        glow: 0.02,
      },
      {
        id: "foam",
        name: "Foam",
        enabled: true,
        color: "#9ED8FF",
        colorB: "#6EB4F0",
        viscosity: 0.12,
        roughness: 0.25,
        metallic: 0.4,
        sheen: 0.7,
        glow: 0.12,
      },
    ],
    emitters: [
      {
        id: "Depth field",
        name: "Depth field",
        enabled: true,
        materialId: "depth",
        kind: "field",
        rate: 0.9,
        radius: 0.025,
        uvX: 0.5,
        uvY: 0.5,
        noiseOffset: 0,
      },
      {
        id: "Cobalt sweep",
        name: "Cobalt sweep",
        enabled: true,
        materialId: "cobalt",
        kind: "point",
        rate: 0.7,
        radius: 0.03,
        uvX: 0.3,
        uvY: 0.45,
        noiseOffset: 0,
      },
      {
        id: "Ice rim",
        name: "Ice rim",
        enabled: true,
        materialId: "ice",
        kind: "point",
        rate: 0.5,
        radius: 0.012,
        uvX: 0.75,
        uvY: 0.35,
        noiseOffset: 0.6,
      },
      {
        id: "Foam fleck",
        name: "Foam fleck",
        enabled: true,
        materialId: "foam",
        kind: "point",
        rate: 0.4,
        radius: 0.008,
        uvX: 0.6,
        uvY: 0.7,
        noiseOffset: 1,
      },
    ],
    windStations: [
      {
        id: "Sweep",
        name: "Sweep",
        enabled: true,
        uvX: 0.2,
        uvY: 0.5,
        heading: 0.0,
        speed: 0.2,
        spin: 0.02,
        radius: 0.55,
      },
    ],
    valueEmitters: [],
    valueBindings: [],
  },
  "contributing-presets": {
    ...heroBase,
    viewZoom: 2.15,
    vorticity: 20,
    velocityDecay: 0.45,
    dyeDecay: 0.014,
    seedVelocityScale: 9,
    composerStrength: 20,
    composerBroad: 1.1,
    composerMedium: 1.0,
    composerFine: 0.7,
    noiseScale: 4.2,
    noiseType: "simplex",
    dyeInject: 0.34,
    contrast: 2.3,
    colorTweenSpeed: 0.014,
    wiggleAmount: 0.12,
    windStrength: 9,
    backgroundMode: "gradient",
    backgroundColor: "#2a1028",
    backgroundColorB: "#7a3a28",
    materials: [
      {
        id: "coral",
        name: "Coral",
        enabled: true,
        color: "#FF7A5C",
        colorB: "#FF9A6E",
        viscosity: 0.12,
        roughness: 0.3,
        metallic: 0.15,
        sheen: 0.6,
        glow: 0.35,
      },
      {
        id: "plum",
        name: "Plum",
        enabled: true,
        color: "#5A2048",
        colorB: "#3A1830",
        viscosity: 0.28,
        roughness: 0.5,
        metallic: 0.08,
        sheen: 0.4,
        glow: 0.08,
      },
      {
        id: "peach",
        name: "Molten peach",
        enabled: true,
        color: "#FFB07A",
        colorB: "#FF8860",
        viscosity: 0.1,
        roughness: 0.25,
        metallic: 0.2,
        sheen: 0.65,
        glow: 0.4,
      },
      {
        id: "ember",
        name: "Ember core",
        enabled: true,
        color: "#FFD0A0",
        colorB: "#FFAA70",
        viscosity: 0.08,
        roughness: 0.22,
        metallic: 0.25,
        sheen: 0.7,
        glow: 0.5,
      },
    ],
    emitters: [
      {
        id: "Plum body",
        name: "Plum body",
        enabled: true,
        materialId: "plum",
        kind: "field",
        rate: 0.85,
        radius: 0.022,
        uvX: 0.5,
        uvY: 0.5,
        noiseOffset: 0,
      },
      {
        id: "Coral bloom",
        name: "Coral bloom",
        enabled: true,
        materialId: "coral",
        kind: "point",
        rate: 0.85,
        radius: 0.04,
        uvX: 0.5,
        uvY: 0.48,
        noiseOffset: 0,
      },
      {
        id: "Peach petal",
        name: "Peach petal",
        enabled: true,
        materialId: "peach",
        kind: "point",
        rate: 0.6,
        radius: 0.025,
        uvX: 0.62,
        uvY: 0.58,
        noiseOffset: 0.3,
      },
      {
        id: "Ember spark",
        name: "Ember spark",
        enabled: true,
        materialId: "ember",
        kind: "point",
        rate: 0.45,
        radius: 0.01,
        uvX: 0.38,
        uvY: 0.4,
        noiseOffset: 0.7,
      },
    ],
    windStations: [
      {
        id: "Bloom up",
        name: "Bloom up",
        enabled: true,
        uvX: 0.5,
        uvY: 0.65,
        heading: 0.75,
        speed: 0.15,
        spin: 0.12,
        radius: 0.3,
      },
      {
        id: "Bloom twist",
        name: "Bloom twist",
        enabled: true,
        uvX: 0.45,
        uvY: 0.4,
        heading: 0.15,
        speed: 0.12,
        spin: -0.1,
        radius: 0.22,
      },
    ],
    valueEmitters: [
      {
        id: "breath",
        name: "Warm pulse",
        enabled: true,
        kind: "sine",
        rate: 0.014,
        phase: 0.1,
        from: 0.04,
        to: 0.09,
        scale: 1,
        band: 0,
      },
    ],
    valueBindings: [
      { id: "current", emitterId: "breath", path: "noiseTime", amount: 0.55 },
    ],
  },
};

export const TRANSPARENT_HERO: Partial<FluidConfig> = {
  ...PAGE_HEROES.settings!,
  backgroundMode: "transparent",
  dyeInject: 0.1,
  viewZoom: 2.0,
};
