// All durations are integer frames at 30 fps; portrait is authored independently.
const shot = (id, seconds, preset, title, kicker = "", mode = "field") => ({
  id,
  frames: seconds * 30,
  preset,
  title,
  kicker,
  mode,
});
export const showcase = [
  shot("hook", 7, "aurora", "Living ink.\nInfinite motion.", "FLUID—WALLPAPER"),
  ...["aurora", "ember", "cobalt", "verdant", "porcelain", "obsidian"].map(
    (p, i) =>
      shot(
        p,
        2,
        p,
        p[0].toUpperCase() + p.slice(1),
        `0${i + 1} / SIX STARTING ATMOSPHERES`,
      ),
  ),
  shot(
    "pointer",
    4,
    "cobalt",
    "Make your mark.",
    "STIR · SWIRL · MIX",
    "pointer",
  ),
  shot(
    "materials",
    5,
    "aurora",
    "Tune the material.",
    "COLOR · GLOW · SHEEN",
    "materials",
  ),
  shot(
    "lighting",
    3,
    "obsidian",
    "Shape the light.",
    "ROUGHNESS · METALLIC · SHEEN",
    "lighting",
  ),
  shot(
    "emitters",
    4,
    "ember",
    "Give color a source.",
    "PLACE EMITTERS",
    "emitters",
  ),
  shot("wind", 4, "verdant", "Give motion direction.", "PLACE WIND", "wind"),
  shot(
    "drivers",
    4,
    "aurora",
    "Let controls wander.",
    "PROCEDURAL DRIVERS",
    "drivers",
  ),
  shot(
    "audio",
    10,
    "aurora",
    "Let sound\nshape the flow.",
    "ORIGINAL SOUNDTRACK → AUDIO ANALYSER",
    "audio",
  ),
  shot(
    "backgrounds",
    3,
    "porcelain",
    "Set the stage.",
    "SOLID · GRADIENT · TRANSPARENT",
    "backgrounds",
  ),
  shot(
    "presets",
    2,
    "cobalt",
    "Save your signature.",
    "PRESET SAVE / LOAD",
    "presets",
  ),
  shot(
    "heroes",
    3,
    "aurora",
    "Build it into your world.",
    "NATIVE + REACT HEROES",
    "heroes",
  ),
  shot(
    "music",
    2,
    "obsidian",
    "Your music. Your atmosphere.",
    "OPTIONAL MUSIC-VIDEO CONTROLS",
    "music",
  ),
  shot(
    "liquid",
    7,
    "porcelain",
    "Explore another medium.",
    "Experimental · Two-liquid studio",
    "liquid",
  ),
  shot(
    "distribution",
    5,
    "obsidian",
    "Made for your canvas.",
    "WEB COMPONENT · REACT · DESKTOP HTML · ECO",
    "distribution",
  ),
  shot(
    "close",
    5,
    "aurora",
    "Try it. Tune it.\nMake it yours.",
    "FLUID—WALLPAPER",
    "close",
  ),
];
export const teaser = [
  shot("hook", 4, "aurora", "Living ink.\nInfinite motion.", "FLUID—WALLPAPER"),
  shot("ember", 3, "ember", "Ember", "FIND YOUR ATMOSPHERE"),
  shot("porcelain", 3, "porcelain", "Porcelain", "FIND YOUR ATMOSPHERE"),
  shot("cobalt", 3, "cobalt", "Cobalt", "FIND YOUR ATMOSPHERE"),
  shot(
    "pointer",
    4,
    "cobalt",
    "Make your mark.",
    "STIR · SWIRL · MIX",
    "pointer",
  ),
  shot(
    "audio",
    6,
    "aurora",
    "Let sound\nshape the flow.",
    "AUDIO REACTIVE",
    "audio",
  ),
  shot(
    "close",
    5,
    "aurora",
    "Try it. Tune it.\nMake it yours.",
    "FLUID—WALLPAPER",
    "close",
  ),
];
